# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
    projectRoot: 'my-movies-angular'
    artifactName: 'drop'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build
  displayName: 'npm install and build'


- task: CopyFiles@2
  displayName: 'Copy terraform files'
  inputs:
      SourceFolder: 'terraform'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/terraform'
      cleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy dist to artifacts'
  inputs:
      SourceFolder: 'dist/$(projectRoot)'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
      cleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '$(artifactName)'